Repository jakubriegel/netcalc, pull requests merged in 2018-11, with the labels that each got.

#1 command line args, readme, requirements.txt
  common/values.py
  netcalc_client.py
  netcalc_server.py
  readme.md
  requirements.txt
Labels: enhancement

#3 Added math methods
  .gitignore
  common/values.py
  netcalc_client.py
  netcalc_server.py
Labels: good first issue, project_specification

#4 Stały rozmiar datagramów, pojedyncze wysyłanie przy wynikach sesji, kolejność pól taka jak w zadaniu
  common/Datagram.py
  netcalc_client.py
  netcalc_server.py
Labels: enhancement, project_specification

#5 Implemented quering from server's cdm
  common/Datagram.py
  common/values.py
  netcalc_client.py
  netcalc_server.py
Labels: project_specification
